### ISSUE TITLE
Add gap in storage to Initializable

### ISSUE THREAD

**Issue by DimaStebaev** [OpenZeppelin/openzeppelin-contracts-upgradeable#110]
I used `Initializable` contract implementation from `@openzeppelin/contracts-ethereum-package` repo. It contains private field `______gap` which is 50 slots in contract storage that reserves space for arbitrary changes in the contract in the future.
`Initializable` is a parent contract for almost all my contracts and I think there is the same situation for may other projects.
`Initializable` implementation in the current repo does not have described gap that prevents me from updating from legacy version.

Adding the gap to `Initializable` will solve the compatibility issue with `@openzeppelin/contracts-ethereum-package`.
Besides this having a gap allows future changes what is wide used practice in many other contracts of this repo.

**Comment by frangio** [comment]
(Repeating my reply from #111.) 

Thank you @DimaStebaev. The missing gap this was unfortunately an oversight that we can't undo now, since it would be an incompatible change for the current package.

Thankfully there is an easy workaround that you can implement in your code, [see my reply here](https://forum.openzeppelin.com/t/upgrade-to-contracts-upgradeable-3-3-with-eip712/5200/3).
