### ISSUE TITLE
Initializable: initializer modifier multiple inheritance broken by _isConstructor() check

### ISSUE THREAD

**Issue by playmint-jbr** [OpenZeppelin/openzeppelin-contracts-upgradeable#142]
Require check now includes _isConstructor() check which will never be true with upgradeable contracts as we don't use their constructors. I assume this has been accidentally integrated over from @openzeppelin/contracts repo.

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by Amxx** [comment]
Hello @playmint-jbr 

This is on purpose. While we do not use constructors to initialize the upgradeable contracts themselves, we do perform initialization, using an upgradeable contract's logic, from the constructor of a Proxy.

This check ensure that if a proxy is currently being constructed, and that the initializer is called as part of this construction, then the call is valid. One particular thing to note is that reentrancy cannot happen under such circumstances, because you cannot call a contract being constructed (the proxy).

**Comment by playmint-jbr** [comment]
So you broke multiple inheritance on purpose?

**Comment by Amxx** [comment]
Have you checked [this release note](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v4.4.1)?

**Comment by Amxx** [comment]
And the `Initializable` contract present in `@openzeppelin/contracts` is targeted at being used with upgradeable contracts. It is by design that it's the exact same code on both versions of the repo.

**Comment by playmint-jbr** [comment]
Can you point me to an example where the constructor of a proxy calls an initializer from the constructor? All of the examples I can find in this repo have the initializer as a separate function which is called after construction.

**Comment by playmint-jbr** [comment]
Never mind, found an example here https://eips.ethereum.org/EIPS/eip-1822#erc-20-token
