### ISSUE TITLE
ERC2771ContextUpgradeable uses constructor instead of initializer

### ISSUE THREAD

**Issue by kevupton** [OpenZeppelin/openzeppelin-contracts-upgradeable#143]
I am not sure this is intentional, but I notice that in `v4.5` has reverted using the `_init` methods to using a constructor. 
Please close this is if this is intentional.

[Currently release-v4.5](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/release-v4.5/contracts/metatx/ERC2771ContextUpgradeable.sol#L14)
```solidity
    /// @custom:oz-upgrades-unsafe-allow state-variable-immutable
    address private immutable _trustedForwarder;

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor(address trustedForwarder) {
        _trustedForwarder = trustedForwarder;
    }
```

[Previously release-v4.4](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/release-v4.4/contracts/metatx/ERC2771ContextUpgradeable.sol)
```solidity
    address private _trustedForwarder;

    function __ERC2771Context_init(address trustedForwarder) internal onlyInitializing {
        __Context_init_unchained();
        __ERC2771Context_init_unchained(trustedForwarder);
    }

    function __ERC2771Context_init_unchained(address trustedForwarder) internal onlyInitializing {
        _trustedForwarder = trustedForwarder;
    }
```

**Comment by Amxx** [comment]
Hello @kevupton 

Yes this is intentional. 

We believe that having the `_trustedForwarder` in storage, like it used to be the case, make all calls to `_msgSender` significantly more expensive. As there are many such call, the overall impact was really bad. This is addressed by using an immutable variable.

The downside of immutable variable is that:
- they cannot be updated 
  → we don't think its an issue here, as we don't expect the ERC2771 forwarder to change without a contract upgrade
- for upgradeable contract, the forwarder address is hardcoded in the implementation, and all proxy using the same implementation will automatically use the same forwarder 
  → again, we think this is reasonable. If a proxy wants to use a different forwarder, it will have to upgrade to another implemenation.

**Comment by frangio** [comment]
Constructors like this are supported in recent versions of OpenZeppelin Upgrades Plugins by providing `constructorArgs` as an option.

**Comment by kevupton** [comment]
Yeh ok no problem! Thanks for the detailed clarification @Amxx
