### ISSUE TITLE
Pre-deployed implementation contracts

### ISSUE THREAD

**Issue by JonahGroendal** [OpenZeppelin/openzeppelin-contracts-upgradeable#176]
**🧐 Motivation**
Save money by not having to deploy implementation contracts

**📝 Details**
Would it be possible to keep an official list of already-deployed implementation contracts? That way each project doesn't have to re-deploy the same implementations and can just deploy the proxies.
Or, better yet, could functionality be built in to the `deployProxy` tuffle/hardhat plugin to search the blockchain for existing implementation contracts so that new ones don't need to be deployed?

**Comment by frangio** [comment]
We've done this in the past. It's a big effort to deploy them, and the benefits are not clear because users often customize their contracts and pre-deployed implementations would not satisfy those needs. Now with all the chains there are the effort to maintain all of these deployments would be massive. It is not something we're interesting in reevaluating for the moment.
