### ISSUE TITLE
Restriction on access roles

### ISSUE THREAD

**Issue by haraldini** [OpenZeppelin/openzeppelin-contracts-upgradeable#40]
Not sure if this is a bug or intentional feature, but looks like all the roles in 
https://github.com/OpenZeppelin/openzeppelin-eth/blob/master/contracts/access/roles/

only restrict the `addRole` function to an account with the same level of permission. This does not allow for hirachial permissions.  Any Minter role for instance can add more minters to the contract

Also the `renounceMinter` seems to be not restricted at all

**Comment by nventuro** [comment]
Hey there @haraldini! I believe this has been answered at some point, but can't find the issue :/ 

The gist of it is, disallowing `add` but allowing `transfer` (which was the old `Ownable` interface) lets you set up a scenario where you transfer the role to a contract that will forward all calls made to it from a certain set of addresses, which is essentially equivalent to giving the role to all of those addresses. Because of this implicit capability inherent in `transfer`, we decided to explicitly make `add` work for role-havers. What sort of hierarchical permission scheme did you have in mind?

Regarding `renounce` functions, they are indeed not restricted, but it only removes the caller's role.

**Comment by akshatdev0** [comment]
I also came across of this use-case.

I think we can achieve it like this:

```
library Ranks {
  struct Rank {
    mapping (address => uint8) rank;
  }

  // Code to configure ranks
}

contract AdminRole is Initializable {
    using Roles for Roles.Role;
    using Ranks for Ranks.Rank;

    event AdminAdded(address indexed account, uint8 rank);
    event AdminRemoved(address indexed account);
    event AdminRankModified(address indexed account, uint8 from, uint8 to);

    Roles.Role private _admins;
    Ranks.Rank private _ranks;

    function initialize() public initializer {
        // Initialize with default admin and ranks
    }

    modifier onlyAdmin(uint8 rank) {
       require(hasAccess(msg.sender, rank));
        _;
    }

    function hasAccess(address account, uint8 rank) public view returns (bool) {
        return (_admins.has(account) && _ranks[account] <= rank);
    }

    // An admin can add admins with rank lower than him
    function addAdmin(address account, uint8 rank) public onlyAdmin(rank-1) {
        _admins.add(account);
        _ranks.add(account, rank);
        emit AdminAdded(account, rank);        
    }

    // Code to configure admins following 'addAdmin' function logic as reference
    
}
```

Following enhancements can be considered:

1. Adding labels to the ranks.
2. Instead of defining separate `Ranks` library, it can be embedded into `Roles` library but only if it makes sense for existing Roles i.e. `MinterRole, CappedRole etc` created with this library.

Please provide views, if anyone have came across such use-case with more features.

**Comment by frangio** [comment]
This no longer applies since we have released the [`AccessControl`](https://docs.openzeppelin.com/contracts/3.x/api/access#AccessControl) contract, which does allow hierarchical permissions as requested in this issue.
